### ISSUE TITLE
Update Intern Recorder for TypeScript Tests

### ISSUE THREAD

**Issue by morrinene** [theintern/recorder#3]
Intern Recorder needs to be updated to allow an option to produce TypeScript tests.  The recorder itself does not necessarily need to be converted to TypeScript, unless it's required.

- Add an option/mode for TS/ES6
 - Verify the code that it’s generating matches the TS/ES6 test format

Be sure to take into consideration work done for the Intern Migration: theintern/intern#674

**Comment by morrinene** [comment]
We pushed this back to the tail end of the conversion project.  We need to confirm how the tests work before updating the recorder to create them.

**Comment by jason0x43** [comment]
Resolved in https://github.com/theintern/recorder/commit/eeef86af7344d8e072a233c4fd8eaa8aa7136a54
